# Generated by Django 4.0.4 on 2022-05-16 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date_time',
        ),
        migrations.AddField(
            model_name='action',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 21, 3, 20, 403132, tzinfo=utc)),
        ),
    ]
