# Generated by Django 4.0.4 on 2022-05-16 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_action_date_time_action_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
