# Generated by Django 4.0.4 on 2022-05-16 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_contract_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portofolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
