# Generated by Django 4.0.4 on 2022-05-17 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_portofolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
