# Generated by Django 4.0.4 on 2022-05-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
