# Generated by Django 4.0.4 on 2022-05-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_manager', '0002_rename_update_at_employee_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
